# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "30MHz CONTEXT"
email: "corjan@30hmz.com"
description: "Sensors"
url: "http://context.30mhz.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-41600887-4"
googleAnalyticsSiteUrl: "context.30mhz.com"
siteVerification: "bKBCNh6Vjb5QQJL8j2-vsuwU6vJqltaIvigE489ErGk"

# Organizer Info
organizerName: "30MHz"
organizerAlternateName: "30MHz B.V."
organizerDescription: "Sensors for everyone!"
organizerEmail: "corjan@30mhz.com"
organizerLogo: "/img/seo/logo_zensie.png"
organizerLink: "http://www.30mhz.com"

# Head
metaKeywords: "event, IoT, amsterdam, future, security, trends, developers, sensor, internet of things, internet of everything, m2m, port of amsterdam, postnl, human, ggz"
twitterAccount: "@30mhz"
socialImageSrcGooglePlus: "/img/seo/logo_zensie.png"
socialImageSrcTwitter: "/img/seo/logo_zensie.png"
socialImageSrcFacebook: "/img/seo/logo_zensie.png"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
# bottomNavigationLinks:
# - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
# rightNavigationButtons:
# - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "#30MHz CONTEXT <typeout> 2015"
eventDate: "Maandag 20 april, 2015"
typeoutTextValues: '"", "The Netherlands","Venezuela", "Colombia", "Spain"'
typeoutFallback: "IoT"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About 30MHz CONTEXT"
aboutBlock:
 - {title: "Sensors", image: "hackathon.jpg", text: "" }
 - {title: "Blog", image: "workshop.jpg", text: "" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "12", specialCharacter: "+", info: "billion mobile connected devices", detail: '<a href="https://gigaom.com/2011/10/13/internet-of-things-will-have-24-billion-devices-by-2020/">by 2020</a>'}
 - {count: "25", specialCharacter: "+", info: "billion wireless connected devices", detail: '<a href="https://gigaom.com/2011/10/13/internet-of-things-will-have-24-billion-devices-by-2020/">by 2020</a>'}
 - {count: "152", specialCharacter: "+", info: "million internet connected cars", detail: '<a href="http://www.autonews.com/article/20140110/OEM06/301109910/the-race-to-market-the-connected-car">by 2020</a>'}
 - {currency: "$", count: "14.4", specialCharacter: "+", info: "trillion IoT related value creation", detail: '<a href="https://agenda.weforum.org/2014/01/are-you-ready-for-the-internet-of-everything/">over the next 10 years</a>'}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "speakers.jpg"
rockstarSpeakersButtonText: "More"
rockstarSpeakersTitle: "Speakers"

rockstarSpeakersCount: 1

# Location Block
locationBlockTitle: "Location"
eventLocationName: "A Lab"
eventLocationLink: "http://a-lab.nl/"
eventStreetAddress: "Overhoeksplein"
eventAddressLocality: "Amsterdam"
eventPostalCode: "1031KS"
eventAddressCountry: "Nederland"
eventStartTime: "2015-04-22T10:00"
eventDoorTime: "09:00"
eventEndTime: "2015-04-20T16:00"
eventPlaceCoordinates: "52.384119, 4.902906"
mapCenterCoordinates: "52.384119, 4.902906"
mapMobileCenterCoordinates: "52.384119, 4.902906"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue1.jpg"
venueSmallImage1: "venue2.jpg"
venueSmallImage2: "venue3.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "A Lab"
venueFeatures: ["A Lab is a place where start-ups and professionals meet, where multidisciplinary creatives within the fields of new media and technology find their peers and can start and house their company."]

# Tweets Feed Block
tweetsFeedImage: "amsterdam.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "30mhzcontext"
#twitterFeed: "https://www.twitter.com/30mhz"

# Partners Block
#organizersTitle: "Organizers"
#partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"
#email: "corjan@30hmz.com"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsOffers:
 -
  name: "Normal"
  price: "150"
  priceCurrency: "EUR"
  ticketsNumber: "30"
  ribbon: "-33%"
  featured: true
  buyButtonLink: "http://www.eventbrite.com/e/onmetelijke-mogelijkheden-2015-tickets-15543755792"
  buyButtonText: "Buy Now"
  ticketContentList: ["The fee of 30MHz Context is € 150,-."]
  validFrom: "2014-08-25T10:00"
  validThrough: "2015-04-19T23:59"

# Footer
socialLinks:
 - {link: "https://www.linkedin.com/company/30mhz", icon: "linkedin"}
 - {link: "https://twitter.com/30mhz", icon: "twitter"}
 - {link: "https://www.facebook.com/30mhz", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.30mhz.com/", text: "30Mhz"}
#   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:corjan@30mhz.com", text: "corjan@30mhz.com"}
# -
#  title: "FAQ"
#  links:
#   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "ZENSIE"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "52.384119, 4.902906"
logisticsMapMobileCenterCoordinates: "52.384119, 4.902906"